services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb_custom
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 10

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress_custom
    container_name: wordpress
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - inception
    restart: unless-stopped
    environment:
      - WP_REDIS_HOST=redis
      - WP_REDIS_PORT=6379

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx_custom
    container_name: nginx
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress
      - static_site
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer_custom
    container_name: adminer
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: unless-stopped
    stop_signal: SIGINT

  static_site:
    build:
      context: ./requirements/bonus/static_site
    image: static_site_custom
    container_name: static_site
    restart: unless-stopped
    networks:
      - inception
    volumes:
      - ./requirements/bonus/static_site/website:/var/www/static:ro

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis_custom
    container_name: redis
    restart: unless-stopped
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  ftp:
    build:
      context: ./requirements/bonus/ftp
    image: ftp_custom
    container_name: ftp
    depends_on:
      - wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - FTP_PASV_ADDRESS=${VM_IP}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - wp_data:/home/${FTP_USER}/wordpress
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    networks:
      - inception

  portainer:
    build:
      context: ./requirements/bonus/portainer
    image: portainer_custom
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    networks:
      - inception
    command:
      - --http-enabled
      - --data=/data

networks:
  inception:
    name: inception
    driver: bridge


volumes:
  mariadb_data:
    external: true
    name: srcs_mariadb_data
  wp_data:
    external: true
    name: srcs_wp_data
  portainer_data:
    external: true
    name: srcs_portainer_data