FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y mariadb-server mariadb-client \
	&& rm -rf /var/lib/apt/lists/*

# dans le Dockerfile, ajouter :
RUN mkdir -p /run/mysqld && chown -R mysql:mysql /run/mysqld

COPY conf/my.cnf /etc/mysql/my.cnf
COPY --chmod=0755 tools/entrypoint.sh /tools/entrypoint.sh

ENTRYPOINT ["/tools/entrypoint.sh"]