FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends vsftpd ca-certificates gettext-base \
 && echo "/usr/sbin/nologin" >> /etc/shells \
 && rm -rf /var/lib/apt/lists/*

COPY conf/vsftpd.conf /tmp/vsftpd.conf
# On ne substitue QUE l'IP passive
RUN envsubst '${FTP_PASV_ADDRESS}' < /tmp/vsftpd.conf > /etc/vsftpd.conf

COPY tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh && mkdir -p /var/run/vsftpd/empty

EXPOSE 21 40000-40005
CMD ["/entrypoint.sh"]