FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends vsftpd ca-certificates gettext-base \
 && echo "/usr/sbin/nologin" >> /etc/shells \
 && rm -rf /var/lib/apt/lists/*

# vsftpd a besoin de ce répertoire pour fonctionner
RUN mkdir -p /var/run/vsftpd/empty

# On copie un template de conf
COPY conf/vsftpd.conf /etc/vsftpd.conf.tmpl

COPY tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 21 40000-40005
CMD ["/entrypoint.sh"]