FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    php-fpm php-mysql curl ca-certificates tar less \
 && rm -rf /var/lib/apt/lists/*

# PHP-FPM: écoute TCP:9000 (chemin version-agnostic)
RUN sed -i 's|^listen = .*|listen = 0.0.0.0:9000|' /etc/php/*/fpm/pool.d/www.conf

# ⚠️ Place WP dans un répertoire "source" qui NE sera PAS recouvert par le volume
RUN mkdir -p /usr/src && \
    curl -fsSL https://wordpress.org/latest.tar.gz | tar -xz -C /usr/src && \
    mv /usr/src/wordpress /usr/src/wordpress-src

# Entrypoint
COPY --chmod=0755 tools/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]