FROM debian:bookworm-slim

WORKDIR /opt/portainer

RUN apt-get update && apt-get install -y curl ca-certificates tar && \
    curl -fSL "https://github.com/portainer/portainer/releases/download/2.21.1/portainer-2.21.1-linux-arm64.tar.gz" \
    | tar -xz -C /opt/portainer && \
    chmod +x /opt/portainer/portainer/portainer && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

EXPOSE 9000 9443 8000

ENTRYPOINT ["/opt/portainer/portainer/portainer"]
