FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
      nginx openssl gettext-base && \
    rm -rf /var/lib/apt/lists/*

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf.tpl

COPY tools/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh && mkdir -p /etc/nginx/ssl

EXPOSE 443

CMD ["/entrypoint.sh"]