FROM debian:bookworm

RUN apt-get update -y \
 && apt-get install -y redis-server ca-certificates \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 6379

CMD ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]